// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260102151724_PatientSpecies")]
    partial class PatientSpecies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActiveSubstanceMedication", b =>
                {
                    b.Property<int>("ActiveSubstancesId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicationsId")
                        .HasColumnType("integer");

                    b.HasKey("ActiveSubstancesId", "MedicationsId");

                    b.HasIndex("MedicationsId");

                    b.ToTable("ActiveSubstanceMedication");
                });

            modelBuilder.Entity("AdmissionReasonPatient", b =>
                {
                    b.Property<int>("AdmissionReasonsId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientsId")
                        .HasColumnType("integer");

                    b.HasKey("AdmissionReasonsId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("AdmissionReasonPatient");
                });

            modelBuilder.Entity("Api.Database.Entities.Account.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeaconId")
                        .HasColumnType("integer");

                    b.Property<string>("BeaconInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Cars")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PushSubscription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Api.Database.Entities.Account.ResetPasswordRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ResetPasswordRequests");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Locations.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Locations.Pen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Pens");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Admission.AdmissionReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdmissionReasons");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Admission.Admitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BeaconId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admitters");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Admission.InitialLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InitialLocations");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Admission.SuspectedSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SuspectedSpecies");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.Attitude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attitudes");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.BodyCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BodyConditions");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.Dehydration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dehydrations");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttitudeId")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyConditionId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DehydrationId")
                        .HasColumnType("integer");

                    b.Property<int>("ExaminerId")
                        .HasColumnType("integer");

                    b.Property<int?>("MucousMembraneColourId")
                        .HasColumnType("integer");

                    b.Property<int?>("MucousMembraneTextureId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesAgeId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("TemperatureUnit")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemperatureValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("WeightUnit")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WeightValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AttitudeId");

                    b.HasIndex("BodyConditionId");

                    b.HasIndex("DehydrationId");

                    b.HasIndex("ExaminerId");

                    b.HasIndex("MucousMembraneColourId");

                    b.HasIndex("MucousMembraneTextureId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpeciesAgeId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.ExamTreatmentInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamTreatmentInstructions");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.ExamTreatmentMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministrationMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationMethodId");

                    b.HasIndex("ExamId");

                    b.HasIndex("MedicationId");

                    b.ToTable("ExamTreatmentMedications");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.MucousMembraneColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MucousMembraneColours");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.MucousMembraneTexture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MucousMembraneTextures");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.HomeCare.HomeCareMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PatientId");

                    b.ToTable("HomeCareMessages");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.HomeCare.HomeCareRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Dropoff")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Pickup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Requested")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Responded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResponderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ResponderId");

                    b.ToTable("HomeCareRequests");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Husbandry.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Husbandry.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Medications.ActiveSubstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActiveSubstances");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Medications.AdministrationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdministrationMethods");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Medications.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ControlledDrug")
                        .HasColumnType("boolean");

                    b.Property<string>("Distributors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MAHolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PAARLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PharmaceuticalFormId")
                        .HasColumnType("integer");

                    b.Property<string>("SPCLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TherapeuticGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("UKPARLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VMDProductNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VMNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PharmaceuticalFormId");

                    b.HasIndex("TherapeuticGroupId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Medications.PharmaceuticalForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PharmaceuticalForms");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Medications.TargetSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TargetSpecies");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Medications.TherapeuticGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TherapeuticGroups");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Outcome.DispositionReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Communication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DispositionReasons");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Outcome.ReleaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReleaseTypes");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Outcome.TransferLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransferLocations");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Admitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AdmitterId")
                        .HasColumnType("integer");

                    b.Property<int>("BeaconId")
                        .HasColumnType("integer");

                    b.Property<int?>("Disposition")
                        .HasColumnType("integer");

                    b.Property<int?>("DispositionReasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Dispositioned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DispositionerId")
                        .HasColumnType("integer");

                    b.Property<string>("FoundAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitialLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PenId")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReleaseTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeciesVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SuspectedSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("TransferLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueIdentifier")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdmitterId");

                    b.HasIndex("DispositionReasonId");

                    b.HasIndex("DispositionerId");

                    b.HasIndex("InitialLocationId");

                    b.HasIndex("PenId");

                    b.HasIndex("ReleaseTypeId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("SpeciesVariantId");

                    b.HasIndex("SuspectedSpeciesId");

                    b.HasIndex("TransferLocationId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.PatientMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Moved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("ToId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ToId");

                    b.ToTable("PatientMovements");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.PatientNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Noted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoterId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("text");

                    b.Property<decimal?>("WeightValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NoterId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientNotes");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.PatientRecheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Due")
                        .HasColumnType("date");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Rechecked")
                        .HasColumnType("date");

                    b.Property<int?>("RecheckerId")
                        .HasColumnType("integer");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RecheckerId");

                    b.ToTable("PatientRechecks");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientPrescriptionInstructions");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionInstructionAdministration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Administered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientPrescriptionInstructionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("PatientPrescriptionInstructionId");

                    b.ToTable("PatientPrescriptionInstructionAdministrations");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministrationMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityValue")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationMethodId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientPrescriptionMedications");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionMedicationAdministration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Administered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientPrescriptionMedicationId")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("PatientPrescriptionMedicationId");

                    b.ToTable("PatientPrescriptionMedicationAdministrations");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.SpeciesAge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociatedVariantId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedVariantId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("SpeciesAges");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.SpeciesVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FeedingGuidance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("SpeciesVariants");
                });

            modelBuilder.Entity("Api.Database.Entities.Notices.Notice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("Api.Database.Entities.Notices.NoticeAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NoticeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId");

                    b.ToTable("NoticeAttachments");
                });

            modelBuilder.Entity("Api.Database.Entities.Notices.NoticeInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Closed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoticeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Opened")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("NoticeId");

                    b.ToTable("NoticeInteractions");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.AssignableArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AssignableAreas");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.AssignableShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("TimeId");

                    b.ToTable("AssignableShifts");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("AttendanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AttendanceId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomMissingReason")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int?>("MissingReasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JobId");

                    b.HasIndex("MissingReasonId");

                    b.HasIndex("TimeId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.AttendanceClocking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("integer");

                    b.Property<string>("Car")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("In")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("Out")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.ToTable("AttendanceClockings");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeaconAssociatedRole")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("CanAlsoDoJobIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("ShowOthersInJobIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.MissingReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MissingReasons");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.RegularShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JobId");

                    b.HasIndex("TimeId");

                    b.ToTable("RegularShifts");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("Minimum")
                        .HasColumnType("integer");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("TimeId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.TimeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BeaconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("TimeRanges");
                });

            modelBuilder.Entity("DietPatient", b =>
                {
                    b.Property<int>("DietsId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientsId")
                        .HasColumnType("integer");

                    b.HasKey("DietsId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("DietPatient");
                });

            modelBuilder.Entity("MedicationTargetSpecies", b =>
                {
                    b.Property<int>("MedicationsId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("MedicationsId", "TargetSpeciesId");

                    b.HasIndex("TargetSpeciesId");

                    b.ToTable("MedicationTargetSpecies");
                });

            modelBuilder.Entity("PatientTag", b =>
                {
                    b.Property<int>("PatientsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("PatientsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PatientTag");
                });

            modelBuilder.Entity("ActiveSubstanceMedication", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.ActiveSubstance", null)
                        .WithMany()
                        .HasForeignKey("ActiveSubstancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmissionReasonPatient", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Admission.AdmissionReason", null)
                        .WithMany()
                        .HasForeignKey("AdmissionReasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Database.Entities.Account.ResetPasswordRequest", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Locations.Pen", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Locations.Area", "Area")
                        .WithMany("Pens")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.Exam", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Exams.Attitude", "Attitude")
                        .WithMany()
                        .HasForeignKey("AttitudeId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Exams.BodyCondition", "BodyCondition")
                        .WithMany()
                        .HasForeignKey("BodyConditionId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Exams.Dehydration", "Dehydration")
                        .WithMany()
                        .HasForeignKey("DehydrationId");

                    b.HasOne("Api.Database.Entities.Account.Account", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Exams.MucousMembraneColour", "MucousMembraneColour")
                        .WithMany()
                        .HasForeignKey("MucousMembraneColourId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Exams.MucousMembraneTexture", "MucousMembraneTexture")
                        .WithMany()
                        .HasForeignKey("MucousMembraneTextureId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany("Exams")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.SpeciesAge", "SpeciesAge")
                        .WithMany()
                        .HasForeignKey("SpeciesAgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attitude");

                    b.Navigation("BodyCondition");

                    b.Navigation("Dehydration");

                    b.Navigation("Examiner");

                    b.Navigation("MucousMembraneColour");

                    b.Navigation("MucousMembraneTexture");

                    b.Navigation("Patient");

                    b.Navigation("Species");

                    b.Navigation("SpeciesAge");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.ExamTreatmentInstruction", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Exams.Exam", "Exam")
                        .WithMany("TreatmentInstructions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.ExamTreatmentMedication", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.AdministrationMethod", "AdministrationMethod")
                        .WithMany()
                        .HasForeignKey("AdministrationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Exams.Exam", "Exam")
                        .WithMany("TreatmentMedications")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrationMethod");

                    b.Navigation("Exam");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.HomeCare.HomeCareMessage", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.HomeCare.HomeCareRequest", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Account.Account", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Account.Account", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderId");

                    b.Navigation("Patient");

                    b.Navigation("Requester");

                    b.Navigation("Responder");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Medications.Medication", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.PharmaceuticalForm", "PharmaceuticalForm")
                        .WithMany()
                        .HasForeignKey("PharmaceuticalFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.TherapeuticGroup", "TherapeuticGroup")
                        .WithMany()
                        .HasForeignKey("TherapeuticGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PharmaceuticalForm");

                    b.Navigation("TherapeuticGroup");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Patient", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Admission.Admitter", "Admitter")
                        .WithMany()
                        .HasForeignKey("AdmitterId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Outcome.DispositionReason", "DispositionReason")
                        .WithMany()
                        .HasForeignKey("DispositionReasonId");

                    b.HasOne("Api.Database.Entities.Account.Account", "Dispositioner")
                        .WithMany()
                        .HasForeignKey("DispositionerId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Admission.InitialLocation", "InitialLocation")
                        .WithMany()
                        .HasForeignKey("InitialLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Locations.Pen", "Pen")
                        .WithMany()
                        .HasForeignKey("PenId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Outcome.ReleaseType", "ReleaseType")
                        .WithMany()
                        .HasForeignKey("ReleaseTypeId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.SpeciesVariant", "SpeciesVariant")
                        .WithMany()
                        .HasForeignKey("SpeciesVariantId");

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Admission.SuspectedSpecies", "SuspectedSpecies")
                        .WithMany()
                        .HasForeignKey("SuspectedSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Outcome.TransferLocation", "TransferLocation")
                        .WithMany()
                        .HasForeignKey("TransferLocationId");

                    b.Navigation("Admitter");

                    b.Navigation("DispositionReason");

                    b.Navigation("Dispositioner");

                    b.Navigation("InitialLocation");

                    b.Navigation("Pen");

                    b.Navigation("ReleaseType");

                    b.Navigation("Species");

                    b.Navigation("SpeciesVariant");

                    b.Navigation("SuspectedSpecies");

                    b.Navigation("TransferLocation");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.PatientMovement", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Locations.Pen", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany("Movements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Locations.Pen", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("Patient");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.PatientNote", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Noter")
                        .WithMany()
                        .HasForeignKey("NoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany("Notes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noter");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.PatientRecheck", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany("Rechecks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Account.Account", "Rechecker")
                        .WithMany()
                        .HasForeignKey("RecheckerId");

                    b.Navigation("Patient");

                    b.Navigation("Rechecker");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionInstruction", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany("PrescriptionInstructions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionInstructionAdministration", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionInstruction", "PatientPrescriptionInstruction")
                        .WithMany("Administrations")
                        .HasForeignKey("PatientPrescriptionInstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("PatientPrescriptionInstruction");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionMedication", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.AdministrationMethod", "AdministrationMethod")
                        .WithMany()
                        .HasForeignKey("AdministrationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", "Patient")
                        .WithMany("PrescriptionMedications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrationMethod");

                    b.Navigation("Medication");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionMedicationAdministration", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionMedication", "PatientPrescriptionMedication")
                        .WithMany("Administrations")
                        .HasForeignKey("PatientPrescriptionMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("PatientPrescriptionMedication");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.SpeciesAge", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.SpeciesVariant", "AssociatedVariant")
                        .WithMany()
                        .HasForeignKey("AssociatedVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Species", "Species")
                        .WithMany("Ages")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedVariant");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.SpeciesVariant", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Species", "Species")
                        .WithMany("Variants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Api.Database.Entities.Notices.NoticeAttachment", b =>
                {
                    b.HasOne("Api.Database.Entities.Notices.Notice", "Notice")
                        .WithMany()
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Api.Database.Entities.Notices.NoticeInteraction", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Notices.Notice", "Notice")
                        .WithMany()
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.AssignableShift", b =>
                {
                    b.HasOne("Api.Database.Entities.Rota.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Rota.TimeRange", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.Assignment", b =>
                {
                    b.HasOne("Api.Database.Entities.Rota.AssignableArea", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Rota.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.Attendance", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Rota.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Rota.MissingReason", "MissingReason")
                        .WithMany()
                        .HasForeignKey("MissingReasonId");

                    b.HasOne("Api.Database.Entities.Rota.TimeRange", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Job");

                    b.Navigation("MissingReason");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.AttendanceClocking", b =>
                {
                    b.HasOne("Api.Database.Entities.Rota.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.RegularShift", b =>
                {
                    b.HasOne("Api.Database.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Rota.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Rota.TimeRange", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Job");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Api.Database.Entities.Rota.Requirement", b =>
                {
                    b.HasOne("Api.Database.Entities.Rota.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Rota.TimeRange", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("DietPatient", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Husbandry.Diet", null)
                        .WithMany()
                        .HasForeignKey("DietsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicationTargetSpecies", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Medications.TargetSpecies", null)
                        .WithMany()
                        .HasForeignKey("TargetSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientTag", b =>
                {
                    b.HasOne("Api.Database.Entities.Hospital.Patients.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Database.Entities.Hospital.Patients.Husbandry.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Locations.Area", b =>
                {
                    b.Navigation("Pens");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Exams.Exam", b =>
                {
                    b.Navigation("TreatmentInstructions");

                    b.Navigation("TreatmentMedications");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Patient", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Movements");

                    b.Navigation("Notes");

                    b.Navigation("PrescriptionInstructions");

                    b.Navigation("PrescriptionMedications");

                    b.Navigation("Rechecks");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionInstruction", b =>
                {
                    b.Navigation("Administrations");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Prescriptions.PatientPrescriptionMedication", b =>
                {
                    b.Navigation("Administrations");
                });

            modelBuilder.Entity("Api.Database.Entities.Hospital.Patients.Species", b =>
                {
                    b.Navigation("Ages");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
