export const countries = [
  { name: 'Afghanistan', iso2: 'AF', three: '004' },
  { name: 'Åland Islands', iso2: 'AX', three: '248' },
  { name: 'Albania', iso2: 'AL', three: '008' },
  { name: 'Algeria', iso2: 'DZ', three: '012' },
  { name: 'American Samoa', iso2: 'AS', three: '016' },
  { name: 'Andorra', iso2: 'AD', three: '020' },
  { name: 'Angola', iso2: 'AO', three: '024' },
  { name: 'Anguilla', iso2: 'AI', three: '660' },
  { name: 'Antarctica', iso2: 'AQ', three: '010' },
  { name: 'Antigua and Barbuda', iso2: 'AG', three: '028' },
  { name: 'Argentina', iso2: 'AR', three: '032' },
  { name: 'Armenia', iso2: 'AM', three: '051' },
  { name: 'Aruba', iso2: 'AW', three: '533' },
  { name: 'Australia', iso2: 'AU', three: '036' },
  { name: 'Austria', iso2: 'AT', three: '040' },
  { name: 'Azerbaijan', iso2: 'AZ', three: '031' },
  { name: 'Bahamas', iso2: 'BS', three: '044' },
  { name: 'Bahrain', iso2: 'BH', three: '048' },
  { name: 'Bangladesh', iso2: 'BD', three: '050' },
  { name: 'Barbados', iso2: 'BB', three: '052' },
  { name: 'Belarus', iso2: 'BY', three: '112' },
  { name: 'Belgium', iso2: 'BE', three: '056' },
  { name: 'Belize', iso2: 'BZ', three: '084' },
  { name: 'Benin', iso2: 'BJ', three: '204' },
  { name: 'Bermuda', iso2: 'BM', three: '060' },
  { name: 'Bhutan', iso2: 'BT', three: '064' },
  {
    name: 'Bolivia, Plurinational State of',
    iso2: 'BO',
    three: '068',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    iso2: 'BQ',
    three: '535',
  },
  { name: 'Bosnia and Herzegovina', iso2: 'BA', three: '070' },
  { name: 'Botswana', iso2: 'BW', three: '072' },
  { name: 'Bouvet Island', iso2: 'BV', three: '074' },
  { name: 'Brazil', iso2: 'BR', three: '076' },
  {
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    three: '086',
  },
  { name: 'Brunei Darussalam', iso2: 'BN', three: '096' },
  { name: 'Bulgaria', iso2: 'BG', three: '100' },
  { name: 'Burkina Faso', iso2: 'BF', three: '854' },
  { name: 'Burundi', iso2: 'BI', three: '108' },
  { name: 'Cabo Verde', iso2: 'CV', three: '132' },
  { name: 'Cambodia', iso2: 'KH', three: '116' },
  { name: 'Cameroon', iso2: 'CM', three: '120' },
  { name: 'Canada', iso2: 'CA', three: '124' },
  { name: 'Cayman Islands', iso2: 'KY', three: '136' },
  { name: 'Central African Republic', iso2: 'CF', three: '140' },
  { name: 'Chad', iso2: 'TD', three: '148' },
  { name: 'Chile', iso2: 'CL', three: '152' },
  { name: 'China', iso2: 'CN', three: '156' },
  { name: 'Christmas Island', iso2: 'CX', three: '162' },
  { name: 'Cocos (Keeling) Islands', iso2: 'CC', three: '166' },
  { name: 'Colombia', iso2: 'CO', three: '170' },
  { name: 'Comoros', iso2: 'KM', three: '174' },
  { name: 'Congo', iso2: 'CG', three: '178' },
  {
    name: 'Congo, Democratic Republic of the',
    iso2: 'CD',
    three: '180',
  },
  { name: 'Cook Islands', iso2: 'CK', three: '184' },
  { name: 'Costa Rica', iso2: 'CR', three: '188' },
  { name: "Côte d'Ivoire", iso2: 'CI', three: '384' },
  { name: 'Croatia', iso2: 'HR', three: '191' },
  { name: 'Cuba', iso2: 'CU', three: '192' },
  { name: 'Curaçao', iso2: 'CW', three: '531' },
  { name: 'Cyprus', iso2: 'CY', three: '196' },
  { name: 'Czechia', iso2: 'CZ', three: '203' },
  { name: 'Denmark', iso2: 'DK', three: '208' },
  { name: 'Djibouti', iso2: 'DJ', three: '262' },
  { name: 'Dominica', iso2: 'DM', three: '212' },
  { name: 'Dominican Republic', iso2: 'DO', three: '214' },
  { name: 'Ecuador', iso2: 'EC', three: '218' },
  { name: 'Egypt', iso2: 'EG', three: '818' },
  { name: 'El Salvador', iso2: 'SV', three: '222' },
  { name: 'Equatorial Guinea', iso2: 'GQ', three: '226' },
  { name: 'Eritrea', iso2: 'ER', three: '232' },
  { name: 'Estonia', iso2: 'EE', three: '233' },
  { name: 'Eswatini', iso2: 'SZ', three: '748' },
  { name: 'Ethiopia', iso2: 'ET', three: '231' },
  {
    name: 'Falkland Islands (Malvinas)',
    iso2: 'FK',
    three: '238',
  },
  { name: 'Faroe Islands', iso2: 'FO', three: '234' },
  { name: 'Fiji', iso2: 'FJ', three: '242' },
  { name: 'Finland', iso2: 'FI', three: '246' },
  { name: 'France', iso2: 'FR', three: '250' },
  { name: 'French Guiana', iso2: 'GF', three: '254' },
  { name: 'French Polynesia', iso2: 'PF', three: '258' },
  {
    name: 'French Southern Territories',
    iso2: 'TF',
    three: '260',
  },
  { name: 'Gabon', iso2: 'GA', three: '266' },
  { name: 'Gambia', iso2: 'GM', three: '270' },
  { name: 'Georgia', iso2: 'GE', three: '268' },
  { name: 'Germany', iso2: 'DE', three: '276' },
  { name: 'Ghana', iso2: 'GH', three: '288' },
  { name: 'Gibraltar', iso2: 'GI', three: '292' },
  { name: 'Greece', iso2: 'GR', three: '300' },
  { name: 'Greenland', iso2: 'GL', three: '304' },
  { name: 'Grenada', iso2: 'GD', three: '308' },
  { name: 'Guadeloupe', iso2: 'GP', three: '312' },
  { name: 'Guam', iso2: 'GU', three: '316' },
  { name: 'Guatemala', iso2: 'GT', three: '320' },
  { name: 'Guernsey', iso2: 'GG', three: '831' },
  { name: 'Guinea', iso2: 'GN', three: '324' },
  { name: 'Guinea-Bissau', iso2: 'GW', three: '624' },
  { name: 'Guyana', iso2: 'GY', three: '328' },
  { name: 'Haiti', iso2: 'HT', three: '332' },
  {
    name: 'Heard Island and McDonald Islands',
    iso2: 'HM',
    three: '334',
  },
  { name: 'Holy See', iso2: 'VA', three: '336' },
  { name: 'Honduras', iso2: 'HN', three: '340' },
  { name: 'Hong Kong', iso2: 'HK', three: '344' },
  { name: 'Hungary', iso2: 'HU', three: '348' },
  { name: 'Iceland', iso2: 'IS', three: '352' },
  { name: 'India', iso2: 'IN', three: '356' },
  { name: 'Indonesia', iso2: 'ID', three: '360' },
  { name: 'Iran, Islamic Republic of', iso2: 'IR', three: '364' },
  { name: 'Iraq', iso2: 'IQ', three: '368' },
  { name: 'Ireland', iso2: 'IE', three: '372' },
  { name: 'Isle of Man', iso2: 'IM', three: '833' },
  { name: 'Israel', iso2: 'IL', three: '376' },
  { name: 'Italy', iso2: 'IT', three: '380' },
  { name: 'Jamaica', iso2: 'JM', three: '388' },
  { name: 'Japan', iso2: 'JP', three: '392' },
  { name: 'Jersey', iso2: 'JE', three: '832' },
  { name: 'Jordan', iso2: 'JO', three: '400' },
  { name: 'Kazakhstan', iso2: 'KZ', three: '398' },
  { name: 'Kenya', iso2: 'KE', three: '404' },
  { name: 'Kiribati', iso2: 'KI', three: '296' },
  {
    name: "Korea, Democratic People's Republic of",
    iso2: 'KP',
    three: '408',
  },
  { name: 'Korea, Republic of', iso2: 'KR', three: '410' },
  { name: 'Kuwait', iso2: 'KW', three: '414' },
  { name: 'Kyrgyzstan', iso2: 'KG', three: '417' },
  {
    name: "Lao People's Democratic Republic",
    iso2: 'LA',
    three: '418',
  },
  { name: 'Latvia', iso2: 'LV', three: '428' },
  { name: 'Lebanon', iso2: 'LB', three: '422' },
  { name: 'Lesotho', iso2: 'LS', three: '426' },
  { name: 'Liberia', iso2: 'LR', three: '430' },
  { name: 'Libya', iso2: 'LY', three: '434' },
  { name: 'Liechtenstein', iso2: 'LI', three: '438' },
  { name: 'Lithuania', iso2: 'LT', three: '440' },
  { name: 'Luxembourg', iso2: 'LU', three: '442' },
  { name: 'Macao', iso2: 'MO', three: '446' },
  { name: 'Madagascar', iso2: 'MG', three: '450' },
  { name: 'Malawi', iso2: 'MW', three: '454' },
  { name: 'Malaysia', iso2: 'MY', three: '458' },
  { name: 'Maldives', iso2: 'MV', three: '462' },
  { name: 'Mali', iso2: 'ML', three: '466' },
  { name: 'Malta', iso2: 'MT', three: '470' },
  { name: 'Marshall Islands', iso2: 'MH', three: '584' },
  { name: 'Martinique', iso2: 'MQ', three: '474' },
  { name: 'Mauritania', iso2: 'MR', three: '478' },
  { name: 'Mauritius', iso2: 'MU', three: '480' },
  { name: 'Mayotte', iso2: 'YT', three: '175' },
  { name: 'Mexico', iso2: 'MX', three: '484' },
  {
    name: 'Micronesia, Federated States of',
    iso2: 'FM',
    three: '583',
  },
  { name: 'Moldova, Republic of', iso2: 'MD', three: '498' },
  { name: 'Monaco', iso2: 'MC', three: '492' },
  { name: 'Mongolia', iso2: 'MN', three: '496' },
  { name: 'Montenegro', iso2: 'ME', three: '499' },
  { name: 'Montserrat', iso2: 'MS', three: '500' },
  { name: 'Morocco', iso2: 'MA', three: '504' },
  { name: 'Mozambique', iso2: 'MZ', three: '508' },
  { name: 'Myanmar', iso2: 'MM', three: '104' },
  { name: 'Namibia', iso2: 'NA', three: '516' },
  { name: 'Nauru', iso2: 'NR', three: '520' },
  { name: 'Nepal', iso2: 'NP', three: '524' },
  {
    name: 'Netherlands, Kingdom of the',
    iso2: 'NL',
    three: '528',
  },
  { name: 'New Caledonia', iso2: 'NC', three: '540' },
  { name: 'New Zealand', iso2: 'NZ', three: '554' },
  { name: 'Nicaragua', iso2: 'NI', three: '558' },
  { name: 'Niger', iso2: 'NE', three: '562' },
  { name: 'Nigeria', iso2: 'NG', three: '566' },
  { name: 'Niue', iso2: 'NU', three: '570' },
  { name: 'Norfolk Island', iso2: 'NF', three: '574' },
  { name: 'North Macedonia', iso2: 'MK', three: '807' },
  { name: 'Northern Mariana Islands', iso2: 'MP', three: '580' },
  { name: 'Norway', iso2: 'NO', three: '578' },
  { name: 'Oman', iso2: 'OM', three: '512' },
  { name: 'Pakistan', iso2: 'PK', three: '586' },
  { name: 'Palau', iso2: 'PW', three: '585' },
  { name: 'Palestine, State of', iso2: 'PS', three: '275' },
  { name: 'Panama', iso2: 'PA', three: '591' },
  { name: 'Papua New Guinea', iso2: 'PG', three: '598' },
  { name: 'Paraguay', iso2: 'PY', three: '600' },
  { name: 'Peru', iso2: 'PE', three: '604' },
  { name: 'Philippines', iso2: 'PH', three: '608' },
  { name: 'Pitcairn', iso2: 'PN', three: '612' },
  { name: 'Poland', iso2: 'PL', three: '616' },
  { name: 'Portugal', iso2: 'PT', three: '620' },
  { name: 'Puerto Rico', iso2: 'PR', three: '630' },
  { name: 'Qatar', iso2: 'QA', three: '634' },
  { name: 'Réunion', iso2: 'RE', three: '638' },
  { name: 'Romania', iso2: 'RO', three: '642' },
  { name: 'Russian Federation', iso2: 'RU', three: '643' },
  { name: 'Rwanda', iso2: 'RW', three: '646' },
  { name: 'Saint Barthélemy', iso2: 'BL', three: '652' },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    iso2: 'SH',
    three: '654',
  },
  { name: 'Saint Kitts and Nevis', iso2: 'KN', three: '659' },
  { name: 'Saint Lucia', iso2: 'LC', three: '662' },
  {
    name: 'Saint Martin (French part)',
    iso2: 'MF',
    three: '663',
  },
  { name: 'Saint Pierre and Miquelon', iso2: 'PM', three: '666' },
  {
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    three: '670',
  },
  { name: 'Samoa', iso2: 'WS', three: '882' },
  { name: 'San Marino', iso2: 'SM', three: '674' },
  { name: 'Sao Tome and Principe', iso2: 'ST', three: '678' },
  { name: 'Saudi Arabia', iso2: 'SA', three: '682' },
  { name: 'Senegal', iso2: 'SN', three: '686' },
  { name: 'Serbia', iso2: 'RS', three: '688' },
  { name: 'Seychelles', iso2: 'SC', three: '690' },
  { name: 'Sierra Leone', iso2: 'SL', three: '694' },
  { name: 'Singapore', iso2: 'SG', three: '702' },
  { name: 'Sint Maarten (Dutch part)', iso2: 'SX', three: '534' },
  { name: 'Slovakia', iso2: 'SK', three: '703' },
  { name: 'Slovenia', iso2: 'SI', three: '705' },
  { name: 'Solomon Islands', iso2: 'SB', three: '090' },
  { name: 'Somalia', iso2: 'SO', three: '706' },
  { name: 'South Africa', iso2: 'ZA', three: '710' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    iso2: 'GS',
    three: '239',
  },
  { name: 'South Sudan', iso2: 'SS', three: '728' },
  { name: 'Spain', iso2: 'ES', three: '724' },
  { name: 'Sri Lanka', iso2: 'LK', three: '144' },
  { name: 'Sudan', iso2: 'SD', three: '729' },
  { name: 'Suriname', iso2: 'SR', three: '740' },
  { name: 'Svalbard and Jan Mayen', iso2: 'SJ', three: '744' },
  { name: 'Sweden', iso2: 'SE', three: '752' },
  { name: 'Switzerland', iso2: 'CH', three: '756' },
  { name: 'Syrian Arab Republic', iso2: 'SY', three: '760' },
  { name: 'Taiwan, Province of China', iso2: 'TW', three: '158' },
  { name: 'Tajikistan', iso2: 'TJ', three: '762' },
  {
    name: 'Tanzania, United Republic of',
    iso2: 'TZ',
    three: '834',
  },
  { name: 'Thailand', iso2: 'TH', three: '764' },
  { name: 'Timor-Leste', iso2: 'TL', three: '626' },
  { name: 'Togo', iso2: 'TG', three: '768' },
  { name: 'Tokelau', iso2: 'TK', three: '772' },
  { name: 'Tonga', iso2: 'TO', three: '776' },
  { name: 'Trinidad and Tobago', iso2: 'TT', three: '780' },
  { name: 'Tunisia', iso2: 'TN', three: '788' },
  { name: 'Türkiye', iso2: 'TR', three: '792' },
  { name: 'Turkmenistan', iso2: 'TM', three: '795' },
  { name: 'Turks and Caicos Islands', iso2: 'TC', three: '796' },
  { name: 'Tuvalu', iso2: 'TV', three: '798' },
  { name: 'Uganda', iso2: 'UG', three: '800' },
  { name: 'Ukraine', iso2: 'UA', three: '804' },
  { name: 'United Arab Emirates', iso2: 'AE', three: '784' },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    three: '826',
  },
  { name: 'United States of America', iso2: 'US', three: '840' },
  {
    name: 'United States Minor Outlying Islands',
    iso2: 'UM',
    three: '581',
  },
  { name: 'Uruguay', iso2: 'UY', three: '858' },
  { name: 'Uzbekistan', iso2: 'UZ', three: '860' },
  { name: 'Vanuatu', iso2: 'VU', three: '548' },
  {
    name: 'Venezuela, Bolivarian Republic of',
    iso2: 'VE',
    three: '862',
  },
  { name: 'Viet Nam', iso2: 'VN', three: '704' },
  { name: 'Virgin Islands (British)', iso2: 'VG', three: '092' },
  { name: 'Virgin Islands (U.S.)', iso2: 'VI', three: '850' },
  { name: 'Wallis and Futuna', iso2: 'WF', three: '876' },
  { name: 'Western Sahara', iso2: 'EH', three: '732' },
  { name: 'Yemen', iso2: 'YE', three: '887' },
  { name: 'Zambia', iso2: 'ZM', three: '894' },
  { name: 'Zimbabwe', iso2: 'ZW', three: '716' },
];
